### ISSUE TITLE
Figma plugin no longer working as of this past week

### ISSUE THREAD

**Issue by uxmovie** [giliamverheide/figma-inter-letter-spacing#1]
May we expect an update soon? Or, is there a more serious issue?

**Comment by giliamverheide** [comment]
> May we expect an update soon? Or, is there a more serious issue?

Thanks for bringing this to my attention, I'll have a look at this and publish a fix as soon as possible.

**Comment by uxmovie** [comment]
Thanks! I absolutely depend on this plugin for streamlining our team’s
workflow! Thank you for the reply and thank you so much for providing such
a helpful plugin.

**Comment by giliamverheide** [comment]
@uxmovie Fixed in the latest version available in the Figma community: [Inter Letter Spacing](https://www.figma.com/community/plugin/795733302011238428/Inter-Letter-Spacing)

Now also works for text layers that use different font families alongside Inter and different font sizes.
